// frontend/src/utils/ReportExporter.js
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';

// Helper: Format Ksh numbers
const formatKsh = (num) => {
  return new Intl.NumberFormat('en-KE', {
    style: 'currency',
    currency: 'KES',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  }).format(num);
};

// Helper: Get date string
const getReportDate = () => {
  const now = new Date();
  return now.toLocaleString('en-KE', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
};

// 📄 Generate & Download PDF Report
export const downloadPDFReport = (reportData) => {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(20);
  doc.text('Kayoni Graphics — Profit & Inventory Report', 14, 20);
  doc.setFontSize(12);
  doc.text(`Generated: ${getReportDate()}`, 14, 30);
  doc.setLineWidth(0.5);
  doc.line(14, 35, 195, 35);

  // KPI Summary
  const { totals } = reportData;
  const summaryY = 45;
  doc.setFontSize(14);
  doc.text('📊 Key Metrics', 14, summaryY);
  doc.setFontSize(11);
  const metrics = [
    ['Total Revenue', formatKsh(totals.totalRevenueKsh)],
    ['Total Expenses', formatKsh(totals.totalExpensesKsh)],
    ['Net Profit', formatKsh(totals.totalProfitKsh)],
    ['Current Stock Value', formatKsh(totals.totalStockValueKsh)]
  ];

  doc.autoTable({
    startY: summaryY + 8,
    theme: 'grid',
    head: [['Metric', 'Amount (Ksh)']],
    body: metrics,
    headStyles: { fillColor: [37, 99, 235] }, // Blue header
    styles: { fontSize: 10 },
    columnStyles: {
      0: { cellWidth: 60 },
      1: { cellWidth: 40, halign: 'right' }
    }
  });

  // Items Table
  const itemsTableY = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(14);
  doc.text('📦 Inventory Summary', 14, itemsTableY);

  const itemRows = reportData.items.map(item => [
    item.name,
    item.quantityBought,
    formatKsh(item.amountBoughtKsh),
    item.quantitySold,
    formatKsh(item.amountSoldKsh),
    item.currentStock,
    formatKsh(item.profitKsh),
    formatKsh(item.stockValueKsh)
  ]);

  doc.autoTable({
    startY: itemsTableY + 8,
    head: [
      ['Item', 'Bought\n(Qty)', 'Bought\n(Ksh)', 'Sold\n(Qty)', 'Revenue\n(Ksh)', 'In Stock', 'Profit\n(Ksh)', 'Stock Value\n(Ksh)']
    ],
    body: itemRows,
    theme: 'striped',
    headStyles: { fillColor: [22, 163, 74], halign: 'center' }, // Green header
    styles: { fontSize: 9, halign: 'right' },
    columnStyles: {
      0: { halign: 'left', fontStyle: 'bold' },
      6: { textColor: item => item[6].includes('-') ? [220, 38, 38] : [34, 197, 94] } // Red for loss, green for profit
    },
    didParseCell: (data) => {
      // Force line breaks in header
      if (data.section === 'head') {
        data.cell.text = data.cell.text.map(t => t.replace('\\n', '\n'));
      }
    }
  });

  // Footer
  const finalY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text('Report generated by Kayoni Graphics Inventory System', 14, finalY);
  doc.text(`Page 1 of 1`, 0, finalY, { align: 'right' });

  // Download
  doc.save(`Kayoni_Report_${new Date().toISOString().slice(0,10)}.pdf`);
};

// 📊 Generate & Download Excel (XLSX)
export const downloadExcelReport = (reportData) => {
  const { items, totals } = reportData;

  // Sheet 1: Summary
  const summarySheet = [
    ['Kayoni Graphics — Report Summary', ''],
    ['Generated:', getReportDate()],
    [''],
    ['Metric', 'Value (Ksh)'],
    ['Total Revenue', totals.totalRevenueKsh],
    ['Total Expenses', totals.totalExpensesKsh],
    ['Net Profit', totals.totalProfitKsh],
    ['Stock Value', totals.totalStockValueKsh],
    [''],
    ['Note: Values rounded to 2 decimals']
  ];

  // Sheet 2: Items
  const itemsSheet = [
    [
      'Item Name',
      'Qty Bought',
      'Amount Bought (Ksh)',
      'Qty Sold',
      'Revenue (Ksh)',
      'Current Stock',
      'Profit (Ksh)',
      'Stock Value (Ksh)'
    ],
    ...items.map(item => [
      item.name,
      item.quantityBought,
      item.amountBoughtKsh,
      item.quantitySold,
      item.amountSoldKsh,
      item.currentStock,
      item.profitKsh,
      item.stockValueKsh
    ])
  ];

  // Create workbook
  const wb = XLSX.utils.book_new();

  const summaryWS = XLSX.utils.aoa_to_sheet(summarySheet);
  const itemsWS = XLSX.utils.aoa_to_sheet(itemsSheet);

  // Style headers (optional – basic styling)
  const headerStyle = { font: { bold: true, color: { rgb: 'FFFFFF' } }, fill: { fgColor: { rgb: '226622' } } };
  ['A1', 'A4', 'B4'].forEach(cell => { if (summaryWS[cell]) summaryWS[cell].s = headerStyle; });
  ['A1', 'B1', 'C1', 'D1', 'E1', 'F1', 'G1', 'H1'].forEach(cell => { if (itemsWS[cell]) itemsWS[cell].s = headerStyle; });

  XLSX.utils.book_append_sheet(wb, summaryWS, 'Summary');
  XLSX.utils.book_append_sheet(wb, itemsWS, 'Items');

  // Generate Excel file
  const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  const blob = new Blob([wbout], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  
  saveAs(blob, `Kayoni_Report_${new Date().toISOString().slice(0,10)}.xlsx`);
};

// 📥 CSV (simpler alternative)
export const downloadCSVReport = (reportData) => {
  const { items } = reportData;

  const headers = [
    'Item Name',
    'Qty Bought',
    'Amount Bought (Ksh)',
    'Qty Sold',
    'Revenue (Ksh)',
    'Current Stock',
    'Profit (Ksh)',
    'Stock Value (Ksh)'
  ];

  const rows = items.map(item => [
    `"${item.name}"`,
    item.quantityBought,
    item.amountBoughtKsh,
    item.quantitySold,
    item.amountSoldKsh,
    item.currentStock,
    item.profitKsh,
    item.stockValueKsh
  ]);

  let csvContent = 'data:text/csv;charset=utf-8,';
  csvContent += headers.join(',') + '\n';
  csvContent += rows.map(e => e.join(',')).join('\n');

  const encodedUri = encodeURI(csvContent);
  const link = document.createElement('a');
  link.setAttribute('href', encodedUri);
  link.setAttribute('download', `Kayoni_Report_${new Date().toISOString().slice(0,10)}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};